
library(tidyverse)
library(magrittr)
library(openxlsx)
library(readxl)
library(writexl)
library(reshape2)
library(skimr)
library(janitor)
library(lubridate)
library(rio)

install.packages("tidyverse")
install.packages("magrittr")
install.packages("openxlsx")
install.packages("readxl")
install.packages("writexl")
install.packages("reshape2")
install.packages("skimr")
install.packages("janitor")
install.packages("lubridate")
install.packages("rio")
